fix itemAdapter 1.18.2
baked-libs/dough pull request #145
Opened 2022-03-06 16:40 UTC by J3fftw1

Fix for https://pastebin.com/100WXjwW

Apparently the nms changed again in 1.18.2.

This would make it work on 1.18.2 but it would fail at 1.18 and 1.18.1 do we want to separately check that or is this sufficiënt 

My commit name is a little of i thought at first it was for .1.18.1 aswell

2022-03-06 16:41 UTC, WalshyDev commented
Yeah don't just break 1.18 and 1.18.1. Make a new class for 1.18.2 specifically

2022-03-06 16:51 UTC, J3fftw1 commented
How do you guys feel about the class name?

2022-03-06 17:38 UTC, md5sha256 commented
I think this is probably fine. However, do we have a policy as to what versions we support/when we drop support for legacy minor versions?

2022-03-06 22:07 UTC, WalshyDev commented
> However, do we have a policy as to what versions we support/when we drop support for legacy minor versions?

We do not right now. It isn't been bad to support 1.14-1.18 so far. Though, if we see NMS changes on patch versions then it may be something to consider more.

---

Regardless, this PR looks good. Do we need any changes to the other NMS classes or is this the only one affected?

2022-03-06 22:09 UTC, J3fftw1 commented
from the report i think its just this

2022-03-06 22:11 UTC, WalshyDev commented
Please update the PR description. Tests should also be done to validate the other cases are ok.

2022-03-07 15:23 UTC, TheBusyBiscuit requested changes
Using an underscore in a class name is not exactly recommended iirc.
We could just use `v` instead here.
Anyway, also spotted a minor mistake with the class visibility, otherwise it looks good to me.
Thanks!

2022-03-07 15:23 UTC, TheBusyBiscuit commented on dough-items/src/main/java/io/github/bakedlibs/dough/items/nms/ItemNameAdapter18_2.java
> +public class ItemNameAdapter18_2 implements ItemNameAdapter {
```suggestion
class ItemNameAdapter18v2 implements ItemNameAdapter {
```

2022-03-07 15:23 UTC, TheBusyBiscuit commented on dough-items/src/main/java/io/github/bakedlibs/dough/items/nms/ItemNameAdapter18_2.java
> +    ItemNameAdapter18_2() throws NoSuchMethodException, SecurityException, ClassNotFoundException, UnknownServerVersionException {
```suggestion
    ItemNameAdapter18v2() throws NoSuchMethodException, SecurityException, ClassNotFoundException, UnknownServerVersionException {
```

2022-03-07 15:23 UTC, TheBusyBiscuit commented on dough-items/src/main/java/io/github/bakedlibs/dough/items/nms/ItemNameAdapter.java
> +                return new ItemNameAdapter18_2();
```suggestion
                return new ItemNameAdapter18v2();
```

2022-03-07 15:35 UTC, TheBusyBiscuit approved these changes
LGTM
@WalshyDev You do a review too and feel free to merge when ready. I will publish a new dough version asap then

2022-03-08 07:07 UTC, md5sha256 approved these changes
LGTM

2022-03-08 07:15 UTC, md5sha256 commented
Although I just remembered that something also broke for the adapter in `dough-skins` from 1.17 to 1.18. Not sure if its affected by this minor revision change but worth double-checking I guess

2022-03-08 13:14 UTC, md5sha256 commented
Just did a quick check, looks like the net.minecraft method is still the same for the adapter in dough-skins so this PR should have everything for 1.18. However, we do need to address the migration of the IS repo (mvn.intellectualsites.com)

2022-03-09 11:09 UTC, WalshyDev commented
Merging, then we'll get @md5sha256's in and release

2022-03-09 11:09 UTC, merged