added a new itemadapter for 1.19
baked-libs/dough pull request #176
Opened 2022-06-07 19:54 UTC by J3fftw1

Updated dough to 1.19
Couldn't test building dough since mypet repo is down again.

Changed Worldedit repo to the enginehub maven repo
added a new ItemAdapter since they changed obf again

2022-06-09 10:27 UTC, J3fftw1 commented
Seems to be ready now. Thanks for the fix @TheBusyBiscuit

2022-06-09 10:34 UTC, TheBusyBiscuit requested changes

2022-06-09 10:34 UTC, TheBusyBiscuit commented on dough-items/src/main/java/io/github/bakedlibs/dough/items/nms/ItemNameAdapter19.java
> +public class ItemNameAdapter19 implements ItemNameAdapter {
This should not be public.
```suggestion
class ItemNameAdapter19 implements ItemNameAdapter {
```

2022-06-10 10:05 UTC, WalshyDev approved these changes

2022-06-10 18:56 UTC, md5sha256 approved these changes
LGTM

2022-06-10 20:06 UTC, TheBusyBiscuit approved these changes
Looks good to me.
Just before I merge this: Does `dough-skins` not need an update for its NMS code?

2022-06-10 20:08 UTC, J3fftw1 commented
> Looks good to me. Just before I merge this: Does `dough-skins` not need an update for its NMS code?

Nope it doesnt. We specifically checked for this.

2022-06-10 20:09 UTC, merged