Feature/custom pdc api types
baked-libs/dough pull request #91
Opened 2021-10-11 20:16 UTC by Sefiraat

## Description
Allows for the use of custom PersistentDataType classes within the PersistentDataAPI

## Proposed changes
A new setter, has and getter(s) accepting a custom PersistentDataType and generic.

Also removed a duplicated @param

## Related Issues (if applicable)
N/A

**Note**: Tested by using the methods in a different plugin before copying here.

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

2022-01-10 01:35 UTC, WalshyDev requested changes

2022-01-10 01:35 UTC, WalshyDev commented on dough-data/src/main/java/io/github/bakedlibs/dough/data/persistent/PersistentDataAPI.java
> +
Comments should be attached to methods
```suggestion
```

2022-01-10 01:35 UTC, WalshyDev commented on dough-data/src/main/java/io/github/bakedlibs/dough/data/persistent/PersistentDataAPI.java
> +
```suggestion
```

2022-01-10 01:36 UTC, WalshyDev submitted a review, later dismissed
LGTM

not sure this is actually smaller than the Spigot API but at least it would create consistency

2022-01-10 01:54 UTC, TheBusyBiscuit reviewed
Do we even need to name this "custom" here?
I think get, set etc... itself is sufficient since you don't specify a "custom" type here, you just specify... *the* type.

2022-01-17 20:58 UTC, WalshyDev approved these changes
LGTM

2022-01-24 15:29 UTC, TheBusyBiscuit approved these changes

2022-01-24 15:30 UTC, merged