Fix issue #75
baked-libs/dough pull request #93
Opened 2021-11-01 14:48 UTC by Angeschossen

This pull requests fixes issue #75. 
The ProtectionManager class now requires the plugin instance that uses dough.

2021-11-01 14:56 UTC, WalshyDev requested changes
Appreciate the PR, tiny fixes

2021-11-01 14:56 UTC, WalshyDev commented on dough-protection/src/main/java/io/github/bakedlibs/dough/protection/modules/LandsProtectionModule.java
> +    private final Plugin lands, plugin;
```suggestion
    private final Plugin lands;
    private final Plugin plugin;
```

2021-11-01 14:56 UTC, WalshyDev commented on dough-protection/src/main/java/io/github/bakedlibs/dough/protection/ProtectionManager.java
> +     *
```suggestion
     * @param plugin
     *            The plugin that uses dough.
```

2022-01-07 22:59 UTC, Sfiguz7 approved these changes
LGTM

2022-01-07 23:03 UTC, WalshyDev approved these changes
LGTM aside one thing

2022-01-07 23:03 UTC, WalshyDev commented on dough-protection/src/main/java/io/github/bakedlibs/dough/protection/ProtectionManager.java
> +    public ProtectionManager(@Nonnull Server server, @Nonnull Plugin plugin) {
Not a big fan of this being named `plugin` but can't think of a better name ccurrently

2022-01-07 23:05 UTC, merged